(require :config.plugins)
(require :config.settings)
(require :config.theme)
(require :config.keybindings)
(require :config.autocommands)
(require :config.lsp)
(require :config.completion)
(require :config.treesitter)
; (require :config.debugger)
(require :config.gtd)
(require :config.meetings)
