unbind-key C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# Reload the file with Prefix r	
bind r source-file ~/.tmux.conf \; display "Reloaded!"	

bind j split-window -h	
bind s split-window -v	

# moving between panes with Prefix h,j,k,l	
bind h select-pane -L	
bind j select-pane -D	
bind k select-pane -U	
bind l select-pane -R	

# Pane resizing panes with Prefix H,J,K,L	
bind -r H resize-pane -L 5	
bind -r J resize-pane -D 5	
bind -r K resize-pane -U 5	
bind -r L resize-pane -R 5	
set -g mouse on	

set -g default-shell $SHELL	
# set -g default-command "reattach-to-user-namespace -l ${SHELL}"	

# Start each new session with four panes:
# top row is 2/3 height, left column is 2/3 width.
set-hook -g after-new-session {
  split-window -h -p 33
  split-window -v -p 33
  select-pane -L
  split-window -v -p 33
  select-pane -t 0
}

# Status line left side to show Session:window:pane	
# set -g status-left-length 40	

# set -g status-justify left
# set -g window-status-format '#{window_index}: #{window_name}'
# set -g window-status-current-format '*#{window_index}: #{window_name}'

# enable activity alerts	
setw -g monitor-activity on	
set -g visual-activity on	
# enable vi keys.	
setw -g mode-keys vi	
bind P paste-buffer	
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection	
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"	
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle	

set-option -g status-interval 1	

# TPM
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'robhurring/tmux-spotify'

set -g status-position top
set -g status-interval 5
set -g status-right-length 120

run-shell '~/.tmux/plugins/tpm/tpm'

# Must be after Gruvbox/TPM, because Gruvbox overwrites status-right
set -g status-right \
  '#(~/.tmux/plugins/tmux-spotify/scripts/status.sh) #(~/.tmux/plugins/tmux-spotify/scripts/artist.sh): #(~/.tmux/plugins/tmux-spotify/scripts/track.sh) | %H:%M  '
