local telescope = require('telescope.builtin')
-- keybindings --
local default_opts = { remap = false }
vim.keymap.set("n", "<Space>", "<Nop>", { silent = true, remap = false })
vim.keymap.set('i', 'jk', '<Esc>')
vim.keymap.set('n', '<C-h>', '<C-w>h', default_opts)
vim.keymap.set('n', '<C-j>', '<C-w>j', default_opts)
vim.keymap.set('n', '<C-k>', '<C-w>k', default_opts)
vim.keymap.set('n', '<C-l>', '<C-w>l', default_opts)
vim.keymap.set('n', '<leader><space>', telescope.find_files, default_opts)
vim.keymap.set('n', '<leader>B', ':bnext<CR>', default_opts)
vim.keymap.set('n', '<leader>D', ':DapContinue<CR>', default_opts)
vim.keymap.set('n', '<leader>S', ":grep -g '!**/**test*' -i ", default_opts)
vim.keymap.set('n', '<leader>W', ':noa w<CR>', default_opts)
vim.keymap.set('n', '<leader>b', ':bprevious<CR>', default_opts)
vim.keymap.set('n', '<leader>c', ':copen<CR>', default_opts)
vim.keymap.set('n', '<leader>d', ':Gvdiff<CR>', default_opts)
vim.keymap.set('n', '<leader>s', ":lua require('telescope').extensions.live_grep_args.live_grep_args()<CR>", default_opts)
vim.keymap.set('n', '<leader>t', ':belowright sp | b zsh<CR>', default_opts)
vim.keymap.set('n', '<leader>w', ':w<CR>', default_opts)
vim.keymap.set('n', '<leader>wh', '<C-w>h', default_opts)
vim.keymap.set('n', '<leader>wj', '<C-w>j', default_opts)
vim.keymap.set('n', '<leader>wk', '<C-w>k', default_opts)
vim.keymap.set('n', '<leader>wl', '<C-w>l', default_opts)
vim.keymap.set('n', '<leader>wH', '<C-w>H', default_opts)
vim.keymap.set('n', '<leader>wJ', '<C-w>J', default_opts)
vim.keymap.set('n', '<leader>wK', '<C-w>K', default_opts)
vim.keymap.set('n', '<leader>wL', '<C-w>L', default_opts)
vim.keymap.set('n', '<leader>wo', ':only<CR>', default_opts)
vim.keymap.set('n', '<leader>ws', ':sp<CR>', default_opts)
vim.keymap.set('n', '<leader>wv', ':vs<CR>', default_opts)
vim.keymap.set('n', '<leader>;', ':', default_opts)
vim.keymap.set('n', 'Y', '"+y', default_opts)
vim.keymap.set('n', 'gD', ":lua require('dapui').toggle()<CR>", default_opts)
vim.keymap.set('n', 'gb', ':DapToggleBreakpoint<CR>', default_opts)
vim.keymap.set('t', '<C-[>', [[<C-\><C-n>]], default_opts)
vim.keymap.set('t', 'jk', [[<C-\><C-n>]], default_opts)
vim.keymap.set('v', 'Y', '"+y', default_opts)
