local telescope = require('telescope.builtin')
-- keybindings --
local default_opts = { remap = false }
vim.keymap.set('n', '<C-h>', '<C-w>h', default_opts)
vim.keymap.set('n', '<C-j>', '<C-w>j', default_opts)
vim.keymap.set('n', '<C-k>', '<C-w>k', default_opts)
vim.keymap.set('n', '<C-l>', '<C-w>l', default_opts)
vim.keymap.set('n', '<leader>D', ':DapContinue<CR>', default_opts)
vim.keymap.set('n', '<leader>W', ':noa w<CR>', default_opts)
vim.keymap.set('n', '<leader>b', ':belowright sp | b zsh<CR>', default_opts)
vim.keymap.set('n', '<leader>c', ':copen<CR>', default_opts)
vim.keymap.set('n', '<leader>d', ':Gvdiff<CR>', default_opts)
vim.keymap.set('n', 'gb', ':DapToggleBreakpoint<CR>', default_opts)
vim.keymap.set('n', '<leader>p', telescope.find_files, default_opts)
vim.keymap.set('n', '<leader>s', ":lua require('telescope').extensions.live_grep_args.live_grep_args()<CR>", default_opts)
vim.keymap.set('n', '<leader>S', ":grep -g '!**/**test*' -i ", default_opts)
vim.keymap.set('n', '<leader>w', ':w<CR>', default_opts)
vim.keymap.set('t', '<C-[>', [[<C-\><C-n>]], default_opts)
